name: Build and Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Blacklock Code Scanner
        uses: knassar702/testing_action@v1.1
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Optional if using blacklock.yml
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Optional if using blacklock.yml
