name: Build and Scan with Blacklock Code Scanner

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensures the code is available in /github/workspace

      - name: Run Blacklock Code Scanner Action
        uses: knassar702/testing_action@v1.1  # Use your action’s version tag here
        with:
          sonar_projectkey: "1gquF-K8I.RdK8pa"  # Replace with your project key
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}  # Define in GitHub Secrets
          sonar_token: ${{ secrets.SONAR_TOKEN }}  # Define in GitHub Secrets
          exclude: "src/test,src/docs"  # Optional: specify paths to exclude
