name: Build and Scan

on:
  push:
    branches:
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Blacklock Code Scanner Action
        uses: knassar702/testing_action@v1.0
        with:
          sonar_projectkey: "1gquF-K8I.RdK8pa"
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
