name: Run Testing Action

on:
  push:
    branches:
      - main

jobs:
  run-testing-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Testing Action
        uses: knassar702/testing_action@v1.0
        with:
          param1: "example_value1"
          param2: "example_value2"
